/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bean.Cliente;
import bean.Produto;
import dao.ClienteDao;
import dao.ProdutoDao;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Alysson
 */
public class TelaConsultarProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultarUsuarios
     */
    public TelaConsultarProduto() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        setarTabela();
        txtPesquisa.setCaretColor(Color.white);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.consultar();
        
        JTableHeader cabecalho = tabelaProdutos.getTableHeader();
        cabecalho.setFont(new Font("Arial", Font.BOLD, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        txtPesquisa = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        btPesquisar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtPesquisa.setBackground(new java.awt.Color(0, 0, 102));
        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setText("Pesquisar...");
        txtPesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusGained(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        cbFiltro.setBackground(new java.awt.Color(0, 0, 102));
        cbFiltro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbFiltro.setForeground(new java.awt.Color(255, 255, 255));
        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FILTRO", "Código", "Nome", "Marca", "Fornecedor" }));
        cbFiltro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFiltroItemStateChanged(evt);
            }
        });
        cbFiltro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbFiltroPropertyChange(evt);
            }
        });

        tabelaProdutos.setBackground(new java.awt.Color(0, 0, 102));
        tabelaProdutos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tabelaProdutos.setForeground(new java.awt.Color(255, 255, 255));
        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descrição", "Marca", "Custo Unitário", "Preço", "Estoque Mínimo", "Estoque Atual", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(1).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(2).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(3).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(4).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(5).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(6).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(7).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(8).setResizable(false);
        }

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupaIcon.png"))); // NOI18N
        btPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPesquisarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Consultar Produtos");

        btRemover.setBackground(new java.awt.Color(0, 0, 102));
        btRemover.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btRemover.setForeground(new java.awt.Color(255, 255, 255));
        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/removeIcon.png"))); // NOI18N
        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(0, 0, 102));
        btAlterar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/updateIcon.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(524, 524, 524)
                .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addComponent(btAlterar)
                .addGap(74, 74, 74)
                .addComponent(btRemover)
                .addContainerGap(495, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(542, 542, 542))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btRemover});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFiltroItemStateChanged

    }//GEN-LAST:event_cbFiltroItemStateChanged

    private void cbFiltroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbFiltroPropertyChange

    }//GEN-LAST:event_cbFiltroPropertyChange

    private void txtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusGained
        txtPesquisa.setText("");
    }//GEN-LAST:event_txtPesquisaFocusGained

    private void btPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisarMouseClicked
        if(txtPesquisa.getText().equals("") || txtPesquisa.getText().equals("Pesquisar...") || cbFiltro.getSelectedIndex()==0){
            consultar();
        }else{
            ProdutoDao pd = new ProdutoDao();
            ArrayList<Produto> produtos = new ArrayList();

            produtos = pd.consultarFiltro(cbFiltro.getSelectedIndex(), txtPesquisa.getText());

            DefaultTableModel model = (DefaultTableModel) tabelaProdutos.getModel(); 
            model.setNumRows(0);
            
            DecimalFormat df = new DecimalFormat("#,###0.00");
        
            for(Produto p: produtos){
                String custo = "R$ "+df.format(p.getCustoUnitario());
                String preco = "R$ "+df.format(p.getPreco());
                model.addRow(new Object[]{p.getCodigo(), p.getNome(), p.getDescricao(), p.getMarca(), custo, preco, p.getEstoqueMinimo(), p.getEstoqueAtual(), p.getFornecedor()});
            }
        }
    }//GEN-LAST:event_btPesquisarMouseClicked

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int linha = tabelaProdutos.getSelectedRow();
        
        if(linha!=-1){
            int op = JOptionPane.showConfirmDialog(null, "Deseja remover o produto "+tabelaProdutos.getValueAt(linha, 1).toString()+"?", null, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(op==0){
                ProdutoDao pd = new ProdutoDao();
                Produto p = new Produto();
                p.setCodigo(tabelaProdutos.getValueAt(linha, 0).toString());
                pd.excluir(p);
                consultar();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o produto que deseja remover.");
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if(tabelaProdutos.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Selecione o produto que deseja alterar.");
        }else{
            Produto p = new Produto();
            p.setCodigo(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0).toString());
            p.setNome(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 1).toString());
            p.setDescricao(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 2).toString());
            p.setMarca(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 3).toString());
            String custo = tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 4).toString();
            custo = custo.substring(3, custo.length()).replace(",", ".");
            p.setCustoUnitario(Double.parseDouble(custo));
            String preco = tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 5).toString();
            preco = preco.substring(3, preco.length()).replace(",", ".");
            p.setPreco(Double.parseDouble(preco));
            p.setEstoqueMinimo(Integer.parseInt(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 6).toString()));
            p.setEstoqueAtual(Integer.parseInt(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 7).toString()));
            p.setFornecedor(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 8).toString());
            
            TelaAlterarProduto tap = new TelaAlterarProduto(p);
            tap.setLocationRelativeTo(null);
            tap.setVisible(true);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        if(evt.getKeyCode()==10){
            btPesquisarMouseClicked(null);
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.consultar();
    }//GEN-LAST:event_formWindowActivated

    void consultar(){
        ProdutoDao pd = new ProdutoDao();
        ArrayList<Produto> produtos = new ArrayList();
        
        produtos = pd.consultar();
        
        DefaultTableModel model = (DefaultTableModel) tabelaProdutos.getModel(); 
        model.setNumRows(0);
        
        DecimalFormat df = new DecimalFormat("#,###0.00");
        
        
        for(Produto p: produtos){
            String custo = "R$ "+df.format(p.getCustoUnitario());
            String preco = "R$ "+df.format(p.getPreco());
            model.addRow(new Object[]{p.getCodigo(), p.getNome(), p.getDescricao(), p.getMarca(), custo, preco, p.getEstoqueMinimo(), p.getEstoqueAtual(), p.getFornecedor()});
        }
    }
    
    void setarTabela(){
        tabelaProdutos.getParent().setBackground(Color.white);
        
        tabelaProdutos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        
        for(int i=0; i<9; i++){
            tabelaProdutos.getColumnModel().getColumn(i).setPreferredWidth(200);
            tabelaProdutos.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JLabel btPesquisar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox cbFiltro;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
