/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bean.Cliente;
import bean.Pagamento;
import bean.Produto;
import dao.ClienteDao;
import dao.PagamentoDao;
import dao.ProdutoDao;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Alysson
 */
public class TelaConsultarPagamentos extends javax.swing.JFrame {

    String responsavel;
    
    public TelaConsultarPagamentos(String responsavel) {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        setarTabela();
        txtPesquisa.setCaretColor(Color.white);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.responsavel = responsavel;
        this.consultar();
        
        JTableHeader cabecalho = tabelaPagamentos.getTableHeader();
        cabecalho.setFont(new Font("Arial", Font.BOLD, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        txtPesquisa = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPagamentos = new javax.swing.JTable();
        btPesquisar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Pagamentos");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtPesquisa.setBackground(new java.awt.Color(0, 0, 102));
        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setText("Pesquisar...");
        txtPesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusGained(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        cbFiltro.setBackground(new java.awt.Color(0, 0, 102));
        cbFiltro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbFiltro.setForeground(new java.awt.Color(255, 255, 255));
        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FILTRO", "Data", "Motivo", "Fornecedor", "Responsável", "Vencimento", "Classificação" }));
        cbFiltro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFiltroItemStateChanged(evt);
            }
        });
        cbFiltro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbFiltroPropertyChange(evt);
            }
        });

        tabelaPagamentos.setBackground(new java.awt.Color(0, 0, 102));
        tabelaPagamentos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tabelaPagamentos.setForeground(new java.awt.Color(255, 255, 255));
        tabelaPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Motivo", "Fornecedor", "Valor Total", "Responsável", "Valores a Pagar", "Vencimento", "Valores Pagos", "Classificação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPagamentos);

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupaIcon.png"))); // NOI18N
        btPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPesquisarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Consultar Pagamentos");

        btRemover.setBackground(new java.awt.Color(0, 0, 102));
        btRemover.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btRemover.setForeground(new java.awt.Color(255, 255, 255));
        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/removeIcon.png"))); // NOI18N
        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(0, 0, 102));
        btAlterar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/updateIcon.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(495, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(549, 549, 549))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesquisar)
                        .addGap(491, 491, 491))))
            .addGroup(layout.createSequentialGroup()
                .addGap(506, 506, 506)
                .addComponent(btAlterar)
                .addGap(74, 74, 74)
                .addComponent(btRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btRemover});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFiltroItemStateChanged

    }//GEN-LAST:event_cbFiltroItemStateChanged

    private void cbFiltroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbFiltroPropertyChange

    }//GEN-LAST:event_cbFiltroPropertyChange

    private void txtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusGained
        txtPesquisa.setText("");
    }//GEN-LAST:event_txtPesquisaFocusGained

    private void btPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisarMouseClicked
        if(txtPesquisa.getText().equals("") || txtPesquisa.getText().equals("Pesquisar...") || cbFiltro.getSelectedIndex()==0){
            consultar();
        }else{
            PagamentoDao pd = new PagamentoDao();
            ArrayList<Pagamento> pagamentos = new ArrayList();

            pagamentos = pd.consultarFiltro(cbFiltro.getSelectedIndex(), txtPesquisa.getText());

            DefaultTableModel model = (DefaultTableModel) tabelaPagamentos.getModel(); 
            model.setNumRows(0);
            
            DecimalFormat df = new DecimalFormat("#,###0.00");
        
            for(Pagamento p: pagamentos){
                String valorTotal = "R$ "+df.format(p.getValorTotal());
                String valoresAPagar = "R$ "+df.format(p.getValoresAPagar());
                String valoresPagos= "R$ "+df.format(p.getValoresPagos());
                String data = formataData(p.getData());
                String vencimento = formataData(p.getVencimento());
                model.addRow(new Object[]{p.getId(), data, p.getMotivo(), p.getFornecedor(), valorTotal, p.getResponsavel(), valoresAPagar, vencimento, valoresPagos, p.getClassificacao()});
            }
        }
    }//GEN-LAST:event_btPesquisarMouseClicked

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int linha = tabelaPagamentos.getSelectedRow();
        
        if(linha!=-1){
            int op = JOptionPane.showConfirmDialog(null, "Deseja remover o pagamento "+tabelaPagamentos.getValueAt(linha, 0).toString()+"?", null, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(op==0){
                PagamentoDao pd = new PagamentoDao();
                Pagamento p = new Pagamento();
                p.setId(Integer.parseInt(tabelaPagamentos.getValueAt(linha, 0).toString()));
                pd.excluir(p);
                consultar();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o pagamento que deseja remover.");
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if(tabelaPagamentos.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Selecione o pagamento que deseja alterar.");
        }else{
            Pagamento p = new Pagamento();
            p.setId(Integer.parseInt(tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 0).toString()));
            p.setData(tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 1).toString());
            p.setMotivo(tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 2).toString());
            p.setFornecedor(tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 3).toString());
            
            String valorTotal = tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 4).toString();
            valorTotal = valorTotal.substring(3, valorTotal.length()).replace(",", ".");
            p.setValorTotal(Double.parseDouble(valorTotal));
            
            p.setResponsavel(tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 5).toString());
            
            String valoresAPagar = tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 6).toString();
            valoresAPagar = valoresAPagar.substring(3, valoresAPagar.length()).replace(",", ".");
            p.setValoresAPagar(Double.parseDouble(valoresAPagar));
            
            p.setVencimento(tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 7).toString());
            
            String valoresPagos = tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 8).toString();
            valoresPagos = valoresPagos.substring(3, valoresPagos.length()).replace(",", ".");
            p.setValoresPagos(Double.parseDouble(valoresPagos));
            
            p.setClassificacao(tabelaPagamentos.getValueAt(tabelaPagamentos.getSelectedRow(), 9).toString());
            
            TelaAlterarPagamento tap = new TelaAlterarPagamento(p, responsavel);
            tap.setLocationRelativeTo(null);
            tap.setVisible(true);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        if(evt.getKeyCode()==10){
            btPesquisarMouseClicked(null);
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.consultar();
    }//GEN-LAST:event_formWindowActivated

    void consultar(){
        PagamentoDao pd = new PagamentoDao();
        ArrayList<Pagamento> pagamentos = new ArrayList();
        
        pagamentos = pd.consultar();
        
        DefaultTableModel model = (DefaultTableModel) tabelaPagamentos.getModel(); 
        model.setNumRows(0);
        
        DecimalFormat df = new DecimalFormat("#,###0.00");
        
        for(Pagamento p: pagamentos){
            String valorTotal = "R$ "+df.format(p.getValorTotal());
            String valoresAPagar = "R$ "+df.format(p.getValoresAPagar());
            String valoresPagos= "R$ "+df.format(p.getValoresPagos());
            String data = formataData(p.getData());
            String vencimento = formataData(p.getVencimento());
            model.addRow(new Object[]{p.getId(), data, p.getMotivo(), p.getFornecedor(), valorTotal, p.getResponsavel(), valoresAPagar, vencimento, valoresPagos, p.getClassificacao()});
        }
    }
    
    void setarTabela(){
        tabelaPagamentos.getParent().setBackground(Color.white);
        
        tabelaPagamentos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        
        for(int i=0; i<10; i++){
            if(i==0){
                tabelaPagamentos.getColumnModel().getColumn(i).setPreferredWidth(50);
            }else if(i==9){
                tabelaPagamentos.getColumnModel().getColumn(i).setPreferredWidth(250);
            }else{
                tabelaPagamentos.getColumnModel().getColumn(i).setPreferredWidth(200);
            }
            tabelaPagamentos.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
        }
    }
    
    String formataData(String data){
        return data.charAt(8)+""+data.charAt(9)+"/"+data.charAt(5)+""+data.charAt(6)+"/"+data.charAt(0)+""+data.charAt(1)+""+data.charAt(2)+""+data.charAt(3);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JLabel btPesquisar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox cbFiltro;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPagamentos;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
